name: Sync Postman Collection
on:
  push:
    branches:
      - main
jobs:
  postman-sync:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Autosuggest API to Postman Collection
        uses: fluximus-prime/openapi-to-postman-action@v2.0.12
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionUid: ${{ vars.POSTMAN_AUTOSUGGEST_COLLECTION_ID }}
          openApiSpec: discovery/autosuggest.yaml
          options: |
            requestParametersResolution: Example
            exampleParametersResolution: Example
            parametersResolution: Example
            folderStrategy: Tags
            enableOptionalParameters: false

      - name: Upload Bestseller API to Postman Collection
        uses: fluximus-prime/openapi-to-postman-action@v2.0.12
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionUid: ${{ vars.POSTMAN_BESTSELLER_COLLECTION_ID }}
          openApiSpec: discovery/bestseller.yaml
          options: |
            requestParametersResolution: Example
            exampleParametersResolution: Example
            parametersResolution: Example
            folderStrategy: Tags
            enableOptionalParameters: false

      - name: Upload Content Search API to Postman Collection
        uses: fluximus-prime/openapi-to-postman-action@v2.0.12
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionUid: ${{ vars.POSTMAN_CONTENT_SEARCH_COLLECTION_ID }}
          openApiSpec: discovery/content-search.yaml
          options: |
            requestParametersResolution: Example
            exampleParametersResolution: Example
            parametersResolution: Example
            folderStrategy: Tags
            enableOptionalParameters: false

      - name: Upload Recommendations & Pathways API to Postman Collection
        uses: fluximus-prime/openapi-to-postman-action@v2.0.12
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionUid: ${{ vars.POSTMAN_RECS_PATHS_COLLECTION_ID }}
          openApiSpec: discovery/recommendations-pathways.yaml
          options: |
            requestParametersResolution: Example
            exampleParametersResolution: Example
            parametersResolution: Example
            folderStrategy: Tags
            enableOptionalParameters: false

      - name: Upload Search & Category API to Postman Collection
        uses: fluximus-prime/openapi-to-postman-action@v2.0.12
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionUid: ${{ vars.POSTMAN_SEARCH_CATEGORY_COLLECTION_ID }}
          openApiSpec: discovery/search-category.yaml
          options: |
            requestParametersResolution: Example
            exampleParametersResolution: Example
            parametersResolution: Example
            folderStrategy: Tags
            enableOptionalParameters: false

      - name: Upload Email Widget API to Postman Collection
        uses: fluximus-prime/openapi-to-postman-action@v2.0.12
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionUid: ${{ vars.POSTMAN_EMAIL_COLLECTION_ID }}
          openApiSpec: discovery/email-spec.yaml
          options: |
            requestParametersResolution: Example
            exampleParametersResolution: Example
            parametersResolution: Example
            folderStrategy: Tags
            enableOptionalParameters: false
